# Generated by Django 5.2.17 on 2026-09-23 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('ativa', models.BooleanField(default=True)),
                ('monitores', models.ManyToManyField(blank=True, related_name='disciplinas_monitoradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Duvida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('resposta', models.TextField(blank=True)),
                ('situacao', models.CharField(choices=[('AB', 'Aberta'), ('EA', 'Em atendimento'), ('RE', 'Respondida'), ('EN', 'Encerrada')], default='AB', max_length=2)),
                ('aberta_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duvidas_abertas', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duvidas', to='duvidas.disciplina')),
                ('monitor_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duvidas_atendidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dúvida',
                'verbose_name_plural': 'Dúvidas',
                'ordering': ['-aberta_em'],
            },
        ),
    ]
